nvidia-orin: Fix core-image build error
Issue: LIN1022-12248

README file update to add 'pam' in DISTRO_FEATURES to build poky distro.
ERROR:weston was skipped: missing required distro feature 'pam' (not in DISTRO_FEATURES)

Kernel configs added to fix below errors in core-image build.
ERROR: modpost: "host1x_syncpt_read" [nvidia-oot/drivers/pci/endpoint/functions/pci-epf-tegra-vnet.ko] undefined
ERROR: nvidia-oot/drivers/gpu/drm/tegra/rgb.c: implicit declaration of function 'devm_drm_panel_bridge_add'

Signed-off-by: Rajeshkumar Ramasamy <rajeshkumar.ramasamy@windriver.com>