nvidia-orin: fix building issue when ostree feature is enabled
Issue: LIN1025-3126

When building nvidia-orin BSP, there is below error reported:
ERROR: Nothing PROVIDES 'virtual/bootloader'
ERROR: Required build target 'wrlinux-image-std' has no buildable providers.
Missing or unbuildable dependency chain was: ['wrlinux-image-std', 'virtual/bootloader']
Because nvidia-orin BSP doesn't use u-boot as bootloader to provide
'virtual/bootloader'. Therefore, add 'virtual/bootloader' into
ASSUME_PROVIDED to avoid missing provider error, and cleared
OSTREE_SD_UBOOT_WIC1 to avoid related WIC issues when ostree feature
is enabled.

Signed-off-by: Meng Li <Meng.Li@windriver.com>