nvidia-orin: tegraflash cuda-compat-workarounds mkdir for centos
Issue: LIN1022-12247

'install -D' command is not creating and copying the contents in centos.
'install -d' is needed to create the directories in do_install, bbappend files
created to prepend the do_install function for centos.

ERROR: ‘tegra-eks-image/../image/usr/share/tegraflash’: No such file or directory
ERROR: ‘tegra-storage-layout/../image/usr/share/tegraflash’: No such file or directory
ERROR: ‘cuda-compatibility-workarounds/../image/usr/include/cuda-compat-workarounds/bits’: No such file or directory

Signed-off-by: Rajeshkumar Ramasamy <rajeshkumar.ramasamy@windriver.com>